name: HYM-api-components-CI
on:
  pull_request:
    branches: [ develop ]
  push:
    branches: [ develop ]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache node_modules
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-${{github.workflow}}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-${{github.workflow}}-
      - name: Setup NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - run: npm ci
      - run: npm run format
      - run: npm run test:coverage
        env:
          CI: true
      - name: Build project
        if: github.event_name == 'push'
        run: npm run build
      - name: Deploy to TEST environment
        if: github.event_name == 'push'
        run: echo 'DEPLOYNG ${{github.workflow}} TO TEST'
